name: wallpaper
description: Simple wallpaper flutter

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  cloud_firestore: ^0.12.9+6
  flutter_staggered_grid_view: ^0.3.0
  image_picker: 0.6.1+10
  path_provider: ^1.4.0
  permission_handler: ^3.3.0
  sqflite: ^1.1.7+2
  firebase_storage: ^3.0.6
  uuid: ^2.0.2
  rxdart: ^0.22.4
  intl: ^0.16.0
  http: ^0.12.0+2
  cached_network_image: ^2.0.0-rc.1
  tuple: ^1.0.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.8.0


flutter:
  uses-material-design: true
  assets:
    - assets/picture.png
    - assets/drawer_header_image.jpg
  fonts:
    - family: NunitoSans
      fonts:
        - asset: assets/NunitoSans-Regular.ttf
